title: CivilProAction Journal
description: Open Access Journal for Civil Society and Sustainable Development

remote_theme: just-the-docs/just-the-docs

color_scheme: light

search_enabled: true

heading_anchors: true

baseurl: "/civilproaction-journal"
url: "https://civilproaction.github.io"

markdown: kramdown
