title: CivilProAction Journal
description: Open Access Journal for Civil Society and Sustainable Development

theme: just-the-docs

url: https://civilproaction.github.io
baseurl: /civilproaction-journal

color_scheme: light

search_enabled: true

heading_anchors: true

back_to_top: true

footer_content: "© 2026 CivilProAction Journal"

aux_links:
  GitHub Repository:
    - https://github.com/civilproaction/civilproaction-journal

nav_sort: case_sensitive
