title: CivilProAction Journal
description: Open Access Journal for Civil Society and Sustainable Development

theme: minima

baseurl: "/civilproaction-journal"
url: "https://civilproaction.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
